version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hmcts-backend-app
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tasks
      - DB_USER_NAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hmcts-network

  db:
    image: postgres:15-alpine
    container_name: hmcts-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hmcts-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasks"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  hmcts-network:
    driver: bridge

volumes:
  postgres_data:
